'use client';
import './globals.css';
import './layout.css';
import { Inter } from 'next/font/google';
import Navbar from './components/Navbar';
import Footer from './components/Footer';
import { CartProvider } from 'react-use-cart';

const inter = Inter({ subsets: ['latin'] });

// export const metadata = {
//   title: 'Graduation Project',
//   description: 'Generated by create next app',
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>TeaJourney</title>
      </head>
      <body
        className={inter.className}
        // style={{
        //   backgroundImage: 'url("images/bg.jpg")',
        //   backgroundSize: 'cover',
        //   backgroundRepeat: 'no-repeat',
        //   backgroundAttachment: 'fixed',
        // }}
      >
        <div className="min-h-screen flex flex-col background-container">
          <CartProvider>
            <Navbar />
            {children}
            <Footer />
          </CartProvider>
        </div>
      </body>
    </html>
  );
}
